### ISSUE TITLE
Spaces in ASCII encoding break author list in BibTeX

### ISSUE THREAD

**Issue by nilsvu** [mcmtroffaes/latexcodec#96]
Example:

```py
import codecs
import latexcodec

codecs.encode("François", "ulatex+") # Fran\\c cois
```

Now in BibTeX, the space in `\c c` is interpreted as delimiting two names. Therefore, it renders as `F.~c.` when it should render as `F.`.

A possible resolution would be to avoid spaces in the encoding, and use braces instead: `\c{c}`. Note that this also what `pylatexenc` does. Would that be a reasonable change?

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Eventually, this is an issue with bibtex not handling latex correctly. I doubt however this will get fixed in bibtex any time soon.

But yes, the design of latexcodec is not to add/remove curly braces. The reason it does that is that it does not really parse latex at all, it just does some fairly simple pattern recognition and replacement for simple cases, and tries to keep a one-to-one correspondence as much as possible. On the other hand, pylatexenc is a full fledged parser and can handle this much more elegantly. I think pylatexenc will serve your needs much better, as it is much easier to customize and much more powerful.

If you have control over the bibtex file yourself, then the other solution is to write "Fran{ç}ois" in the original bibtex. This will then get translated to ""Fran{\c c}ois" (or "Fran\c{c}ois", I can't recall how exactly the parser handles this case, but it's one of those two) which should be fine for bibtex.

**Comment by mcmtroffaes** [comment]
Closing as ``{ç}`` seems like a reasonable workaround for bibtex's limitations.

**Comment by nilsvu** [comment]
ok thanks 👍

**Comment by mcmtroffaes** [comment]
You're welcome. Thanks for taking the time to report!
